name: "CodeQL Analysis"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '0 3 * * 1'  # Ejecutar cada lunes a las 3 AM UTC

jobs:
  dojo:
    name: Defect Dojo
    runs-on: ubuntu-latest
    env:
      DEFECTDOJO_URL: "https://8519-2800-810-5e4-99ae-173e-f75c-5fd7-5460.ngrok-free.app"
      DEFECTDOJO_TOKEN: "e3c422ed03c8c6566dbdba5d6f93c66bb779396d"
      DEFECTDOJO_ENGAGEMENT_PERIOD: 28
      DEFECTDOJO_ENGAGEMENT_STATUS: "Not Started"
      DEFECTDOJO_ENGAGEMENT_BUILD_SERVER: "null"
      DEFECTDOJO_ENGAGEMENT_SOURCE_CODE_MANAGEMENT_SERVER: "null"
      DEFECTDOJO_ENGAGEMENT_ORCHESTRATION_ENGINE: "null"
      DEFECTDOJO_ENGAGEMENT_DEDUPLICATION_ON_ENGAGEMENT: "false"
      DEFECTDOJO_ENGAGEMENT_THREAT_MODEL: "true"
      DEFECTDOJO_ENGAGEMENT_API_TEST: "true"
      DEFECTDOJO_ENGAGEMENT_PEN_TEST: "true"
      DEFECTDOJO_ENGAGEMENT_CHECK_LIST: "true"
      DEFECTDOJO_PRODUCTID: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq coreutils

      - name: Set engagement dates
        run: |
            echo "TODAY=$(date +%Y-%m-%d)" >> $GITHUB_ENV
            echo "ENDDAY=$(date -d '+28 days' +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Create engagement in DefectDojo
        run: |
          ENGAGEMENTID=$(curl --fail --location --request POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
          --header "Authorization: Token df9ab36562a1584ac253353c42313d526dd72a1f" \
          --header "Content-Type: application/json" \
          --data-raw '{
            "tags": ["GitHub Actions"],
            "name": "Trivy_#${{ github.run_id }}",
            "description": "${{ github.event.head_commit.message }}", 
            "version": "${{ github.ref }}",
            "first_contacted": "'"$TODAY"'",
            "target_start": "'"$TODAY"'",
            "target_end": "'"$ENDDAY"'",
            "reason": "Automated engagement",
            "tracker": "https://github.com/${{ github.repository }}",
            "test_strategy": null,
            "threat_model": '${DEFECTDOJO_ENGAGEMENT_THREAT_MODEL}',
            "api_test": '${DEFECTDOJO_ENGAGEMENT_API_TEST}',
            "pen_test": '${DEFECTDOJO_ENGAGEMENT_PEN_TEST}',
            "check_list": '${DEFECTDOJO_ENGAGEMENT_CHECK_LIST}',
            "status": "'"${DEFECTDOJO_ENGAGEMENT_STATUS}"'",
            "engagement_type": "CI/CD",
            "build_id": "${{ github.run_id }}",
            "commit_hash": "${{ github.sha }}",
            "branch_tag": "${{ github.ref_name }}",
            "source_code_management_uri": "https://github.com/${{ github.repository }}",
            "deduplication_on_engagement": '${DEFECTDOJO_ENGAGEMENT_DEDUPLICATION_ON_ENGAGEMENT}',
            "product": 1,
            "build_server": '${DEFECTDOJO_ENGAGEMENT_BUILD_SERVER}',
            "source_code_management_server": '${DEFECTDOJO_ENGAGEMENT_SOURCE_CODE_MANAGEMENT_SERVER}',
            "orchestration_engine": '${DEFECTDOJO_ENGAGEMENT_ORCHESTRATION_ENGINE}'
          }' | jq -r '.id')
          echo "DEFECTDOJO_ENGAGEMENTID=${ENGAGEMENTID}" >> defectdojo.env

      - name: Upload defectdojo.env file
        uses: actions/upload-artifact@v4
        with:
          name: defectdojo-env
          path: defectdojo.env
  
  defectdojo_publish_trivy:
    name: Publish Trivy Scan to DefectDojo
    runs-on: ubuntu-latest
    env:
      DEFECTDOJO_URL: "https://8519-2800-810-5e4-99ae-173e-f75c-5fd7-5460.ngrok-free.app"
      DEFECTDOJO_TOKEN: "df9ab36562a1584ac253353c42313d526dd72a1f"
      DEFECTDOJO_SCAN_MINIMUM_SEVERITY: "Info"
      DEFECTDOJO_SCAN_ACTIVE: "true"
      DEFECTDOJO_SCAN_VERIFIED: "false"
      DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS: "true"
      DEFECTDOJO_SCAN_PUSH_TO_JIRA: "false"
      DEFECTDOJO_SCAN_ENVIRONMENT: "Default"
      DEFECTDOJO_SCAN_TEST_TYPE: "SARIF"
      DEFECTDOJO_PRODUCT_TYPE: "Github Actions"
      DEFECTDOJO_PRODUCT_NAME: "Testing_Prod"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Set scan date
        run: |
            echo "TODAY=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Upload Trivy Scan to DefectDojo
        run: |
          curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
          -H "accept: application/json" \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
          -F "scan_date=${TODAY}" \
          -F "minimum_severity=${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}" \
          -F "active=${DEFECTDOJO_SCAN_ACTIVE}" \
          -F "verified=${DEFECTDOJO_SCAN_VERIFIED}" \
          -F "scan_type=${DEFECTDOJO_SCAN_TEST_TYPE}" \
          -F "product_name=${DEFECTDOJO_PRODUCT_NAME}" \
          -F "file=@trivy-results.sarif;type=application/sarif+json" \
          -F "engagement_name=Trivy_#${{ github.run_id }}" \
          -F "close_old_findings=${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}" \
          -F "push_to_jira=${DEFECTDOJO_SCAN_PUSH_TO_JIRA}"