name: "CodeQL Analysis"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '0 3 * * 1'  # Ejecutar cada lunes a las 3 AM UTC

jobs:
  dojo:
    name: Defect Dojo
    runs-on: ubuntu-latest
    env:
      DEFECTDOJO_URL: "https://8519-2800-810-5e4-99ae-173e-f75c-5fd7-5460.ngrok-free.app"
      DEFECTDOJO_TOKEN: "e3c422ed03c8c6566dbdba5d6f93c66bb779396d"
      DEFECTDOJO_ENGAGEMENT_PERIOD: 28
      DEFECTDOJO_ENGAGEMENT_STATUS: "Not Started"
      DEFECTDOJO_ENGAGEMENT_BUILD_SERVER: "null"
      DEFECTDOJO_ENGAGEMENT_SOURCE_CODE_MANAGEMENT_SERVER: "null"
      DEFECTDOJO_ENGAGEMENT_ORCHESTRATION_ENGINE: "null"
      DEFECTDOJO_ENGAGEMENT_DEDUPLICATION_ON_ENGAGEMENT: "false"
      DEFECTDOJO_ENGAGEMENT_THREAT_MODEL: "true"
      DEFECTDOJO_ENGAGEMENT_API_TEST: "true"
      DEFECTDOJO_ENGAGEMENT_PEN_TEST: "true"
      DEFECTDOJO_ENGAGEMENT_CHECK_LIST: "true"
      DEFECTDOJO_PRODUCTID: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq coreutils

      - name: Set engagement dates
        run: |
          TODAY=$(date +%Y-%m-%d)
          ENDDAY=$(date -d "+28 days" +%Y-%m-%d)
          echo "TODAY=${TODAY}"
          echo "ENDDAY=${ENDDAY}"

      - name: Create engagement in DefectDojo
        run: |
          ENGAGEMENTID=$(curl --fail --location --request POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
          --header "Authorization: Token df9ab36562a1584ac253353c42313d526dd72a1f" \
          --header "Content-Type: application/json" \
          --data-raw '{
            "tags": ["GitHub Actions"],
            "name": "Trivy_#${GITHUB_RUN_ID}",
            "description": "Trivy",
            "version": "Version 1.0",
            "first_contacted": "2025-03-16",
            "target_start": "2025-03-16",
            "target_end": "2025-03-16",
            "reason": "string",
            "tracker": "https://github.com/gastonbarbaccia",
            "test_strategy": null,
            "threat_model": true,
            "api_test": true,
            "pen_test": true,
            "check_list": true,
            "status": "Not Started",
            "engagement_type": "CI/CD",
            "build_id": "string",
            "commit_hash": "string",
            "branch_tag": "string",
            "source_code_management_uri": "https://github.com/gastonbarbaccia",
            "deduplication_on_engagement": true,
            "product": 1,
            "build_server": null,
            "source_code_management_server": null,
            "orchestration_engine": null
          }' | jq -r '.id')
          echo "DEFECTDOJO_ENGAGEMENTID=${ENGAGEMENTID}" >> defectdojo.env

      - name: Upload defectdojo.env file
        uses: actions/upload-artifact@v4
        with:
          name: defectdojo-env
          path: defectdojo.env